services:
  - type: web
    name: Toxic-MD
    env: docker
    region: Singapore
    plan: free
    repo: https://github.com/xhclintohn/Toxic-Md 
    autoDeploy: true 
    envVars:
      - key: SESSION_ID
        sync: false  # Requires manual input in the Render Dashboard
        description: ğŸ” Your botâ€™s session ID. Scan the QR code to get this or the bot wonâ€™t start!